
[[constraint]]
  branch = "v1"
  name = "gopkg.in/unrolled/render.v1"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.45.3"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/pat"
  version = "1.0.0"

[[constraint]]
  name = "github.com/codegangsta/negroni"
  version = "0.3.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.9.1"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  name = "github.com/labstack/echo-contrib"
  version = "0.5.2"
